name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build main.go
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows binary
        path: main.exe
